flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- argparser-0.3.4
- distributed-process-simplelocalnet-0.2.3.2
- distributed-process-client-server-0.1.3.2
- distributed-process-extras-0.2.1.2
- distributed-process-task-0.1.2.2
- distributed-process-async-0.2.3
resolver: lts-5.8
