flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- data-hash-0.2.0.1
- time-1.5.0.1 # find some middle-ground here
- distributed-process-0.5.5.1
- distributed-process-async-0.2.3
- distributed-process-client-server-0.1.3.2
- distributed-process-extras-0.2.1.2
- distributed-process-simplelocalnet-0.2.3.2
- network-transport-tcp-0.4.2
- reactive-banana-1.1.0.0
- logging-3.0.4
- file-embed-0.0.10
resolver: lts-5.16
